import { Listing, User, AdBanner } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'ProGamer_X',
    email: 'progamer@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ProGamer',
    type: 'seller',
    rating: 4.9,
    totalSales: 247,
    joinedAt: new Date('2023-01-15'),
    isVerified: true,
  },
  {
    id: '2',
    username: 'NightHawk99',
    email: 'nighthawk@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NightHawk',
    type: 'seller',
    rating: 4.7,
    totalSales: 183,
    joinedAt: new Date('2023-03-22'),
    isVerified: true,
  },
  {
    id: '3',
    username: 'DesertStorm_EG',
    email: 'desert@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Desert',
    type: 'seller',
    rating: 4.8,
    totalSales: 312,
    joinedAt: new Date('2022-11-08'),
    isVerified: true,
  },
  {
    id: '4',
    username: 'PhoenixRise',
    email: 'phoenix@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Phoenix',
    type: 'seller',
    rating: 4.6,
    totalSales: 95,
    joinedAt: new Date('2023-06-10'),
    isVerified: false,
  },
];

export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'Valorant Immortal 3 Account — Full Skin Collection',
    titleAr: 'حساب فالورانت إيموورتال ٣ — مجموعة سكنات كاملة',
    description: 'Fully loaded Valorant account with 200+ skins including Elderflame, Prime, and Reaver collections. Immortal 3 rank, 800+ wins. All agents unlocked.',
    descriptionAr: 'حساب فالورانت مكتمل مع أكثر من ٢٠٠ سكن بما فيها مجموعات Elderflame و Prime و Reaver. تصنيف Immortal 3، أكثر من ٨٠٠ فوز. جميع العملاء مفتوحون.',
    price: 4500,
    game: 'Valorant',
    type: 'account',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&q=80',
    rank: 'Diamond',
    seller: mockUsers[0],
    likes: 342,
    isBoosted: true,
    boostType: 'monthly',
    createdAt: new Date('2024-12-01'),
    isAvailable: true,
    stats: { level: 312, hoursPlayed: 2400, winRate: 58 },
  },
  {
    id: '2',
    title: 'Fortnite OG Account — Chapter 1 Skins',
    titleAr: 'حساب فورتنايت أوجي — سكنات الفصل الأول',
    description: 'Rare OG Fortnite account featuring Black Knight, Renegade Raider, and Purple Skull Trooper. Season 1–4 skins. Never banned.',
    descriptionAr: 'حساب فورتنايت نادر من الأيام الأولى يحتوي على Black Knight و Renegade Raider و Purple Skull Trooper. سكنات من المواسم ١ إلى ٤.',
    price: 8900,
    game: 'Fortnite',
    type: 'account',
    coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    rank: 'Gold',
    seller: mockUsers[1],
    likes: 891,
    isBoosted: true,
    boostType: 'weekly',
    createdAt: new Date('2024-12-05'),
    isAvailable: true,
    stats: { level: 580, hoursPlayed: 4100 },
  },
  {
    id: '3',
    title: 'League of Legends Diamond Account — EUW',
    titleAr: 'حساب League of Legends دياموند — EUW',
    description: 'Diamond II support main with 200+ champions. All rune pages filled. Rare skin collection including Lancer Zero Hecarim.',
    descriptionAr: 'حساب دياموند ٢ متخصص في الدعم مع أكثر من ٢٠٠ بطل. جميع صفحات الرونز مكتملة.',
    price: 3200,
    game: 'League of Legends',
    type: 'account',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&q=80',
    rank: 'Diamond',
    seller: mockUsers[2],
    likes: 215,
    isBoosted: false,
    createdAt: new Date('2024-12-08'),
    isAvailable: true,
    stats: { level: 246, winRate: 55 },
  },
  {
    id: '4',
    title: 'PUBG Mobile Conqueror Season Account',
    titleAr: 'حساب PUBG موبايل كونكريور موسمي',
    description: 'Conqueror rank achieved for 3 consecutive seasons. Full mythic outfit collection. 2500+ matches played.',
    descriptionAr: 'تم الوصول لرتبة كونكريور لـ ٣ مواسم متتالية. مجموعة الأزياء الميثيك الكاملة.',
    price: 2800,
    game: 'PUBG Mobile',
    type: 'account',
    coverImage: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&q=80',
    rank: 'Master',
    seller: mockUsers[3],
    likes: 178,
    isBoosted: false,
    createdAt: new Date('2024-12-10'),
    isAvailable: true,
    stats: { level: 88, hoursPlayed: 1800, winRate: 12 },
  },
  {
    id: '5',
    title: 'CS2 Global Elite — Prime Status + Knife',
    titleAr: 'حساب CS2 جلوبال إليت — برايم ستاتس + سكين سكين',
    description: 'Global Elite rank with Prime Status. Includes Karambit Fade knife and Dragon Lore AWP. Clean account, no VAC warnings.',
    descriptionAr: 'رتبة Global Elite مع Prime Status. يشمل سكين Karambit Fade وبندقية Dragon Lore AWP.',
    price: 12500,
    game: 'CS2',
    type: 'account',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&q=80',
    rank: 'Master',
    seller: mockUsers[0],
    likes: 567,
    isBoosted: true,
    boostType: 'monthly',
    createdAt: new Date('2024-11-28'),
    isAvailable: true,
    stats: { level: 40, hoursPlayed: 3200, winRate: 62 },
  },
  {
    id: '6',
    title: 'Apex Legends Predator Account — All Heirlooms',
    titleAr: 'حساب Apex Legends برداتور — كل الإيرلومز',
    description: 'Apex Predator with 3 heirloom sets. 15,000+ kills across multiple legends. Season 1 badge.',
    descriptionAr: 'أبكس برداتور مع ٣ مجموعات إيرلوم. أكثر من ١٥,٠٠٠ قتل عبر عدة بطال.',
    price: 7800,
    game: 'Apex Legends',
    type: 'account',
    coverImage: 'https://images.unsplash.com/photo-1548484352-ea579e5233a8?w=600&q=80',
    rank: 'Master',
    seller: mockUsers[2],
    likes: 423,
    isBoosted: false,
    createdAt: new Date('2024-12-03'),
    isAvailable: true,
    stats: { level: 1200, winRate: 18 },
  },
];

export const mockAdBanners: AdBanner[] = [
  {
    id: '1',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1400&q=80',
    linkUrl: '#',
    advertiserName: 'GamePro Store',
    expiresAt: new Date('2025-06-01'),
  },
  {
    id: '2',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1400&q=80',
    linkUrl: '#',
    advertiserName: 'ESports Egypt',
    expiresAt: new Date('2025-06-01'),
  },
  {
    id: '3',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1400&q=80',
    linkUrl: '#',
    advertiserName: 'TechGear Arabia',
    expiresAt: new Date('2025-06-01'),
  },
];
