import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

function getAdmin() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } },
  );
}

/**
 * POST /api/auth/upload-id
 *
 * Called immediately after supabase.auth.signUp() to:
 *  1. Upload the user's ID document to private storage
 *  2. Create a pending verification record
 *
 * Security: checks the userId was created within the last 15 minutes
 * to prevent abuse from unrelated user IDs being submitted.
 */
export async function POST(req: NextRequest) {
  try {
    const form = await req.formData();
    const userId    = form.get('user_id') as string | null;
    const idDocType = form.get('id_doc_type') as string | null;
    const idFile    = form.get('id_doc') as File | null;

    if (!userId || !idDocType || !idFile || idFile.size === 0) {
      return NextResponse.json({ error: 'Missing fields' }, { status: 400 });
    }
    if (idFile.size > 10 * 1024 * 1024) {
      return NextResponse.json({ error: 'File too large (max 10 MB)' }, { status: 400 });
    }
    if (!['national_id', 'passport', 'birth_certificate'].includes(idDocType)) {
      return NextResponse.json({ error: 'Invalid doc type' }, { status: 400 });
    }

    const admin = getAdmin();

    // Security: user must have been created within the last 15 minutes
    const { data: userData, error: userErr } = await admin.auth.admin.getUserById(userId);
    if (userErr || !userData.user) {
      return NextResponse.json({ error: 'Invalid user' }, { status: 400 });
    }
    const createdAt = new Date(userData.user.created_at);
    if (Date.now() - createdAt.getTime() > 15 * 60 * 1000) {
      return NextResponse.json({ error: 'Upload window expired. Please sign in and re-submit.' }, { status: 400 });
    }

    // Upload file to private bucket
    const ext = idFile.name.split('.').pop()?.toLowerCase() ?? 'jpg';
    const filePath = `${userId}/id_doc.${ext}`;
    const bytes = new Uint8Array(await idFile.arrayBuffer());

    const { error: uploadErr } = await admin.storage
      .from('id-documents')
      .upload(filePath, bytes, { contentType: idFile.type, upsert: true });

    if (uploadErr) {
      console.error('[upload-id] storage error:', uploadErr.message);
      return NextResponse.json({ error: 'Upload failed. Please try again.' }, { status: 500 });
    }

    // Insert (or update) verification record — status: pending, awaiting mod review
    const { error: verifErr } = await admin.from('verifications').upsert({
      user_id:     userId,
      id_front_url: filePath,   // stored as path, signed URL generated by mod panel
      id_doc_type:  idDocType,
      status:       'pending',
      submitted_at: new Date().toISOString(),
    }, { onConflict: 'user_id' });

    if (verifErr) {
      console.error('[upload-id] verif insert error:', verifErr.message);
      // Don't block registration — log and continue
    }

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error('[upload-id]', err);
    return NextResponse.json({ error: 'Server error' }, { status: 500 });
  }
}
